### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-i18n#1]
I see that the [update of the `zend-i18n` documentation](https://github.com/froschdesign/zend-documentation-showcase) is frozen for a while.

By parsing through it I could find several files that would have been useful for me today (but some are still marked as to do):
- https://froschdesign.github.io/zend-documentation-showcase/translator/format-examples/
- https://froschdesign.github.io/zend-documentation-showcase/translator/plural-messages/
- https://froschdesign.github.io/zend-documentation-showcase/application-integration/zend-expressive/
- ...

Do you need some help with it @froschdesign ?

---

Originally posted by @jbelien at https://github.com/zendframework/zend-i18n/issues/115

**Comment by weierophinney** [comment]
The current rework is an illustration for the following issues:

* https://github.com/zendframework/documentation/issues/13
* https://github.com/zendframework/documentation/issues/8
* https://github.com/zendframework/documentation/issues/7

I am still working on it and there is already more progress. I hope to complete the work in the next two weeks



---

Originally posted by @froschdesign at https://github.com/zendframework/zend-i18n/issues/115#issuecomment-533144252

**Comment by weierophinney** [comment]
Awesome! Looking forward to it! \o/

---

Originally posted by @jbelien at https://github.com/zendframework/zend-i18n/issues/115#issuecomment-533145331

**Comment by froschdesign** [comment]
The limit of 10 linked pull requests is reached. We will use a project to monitor progress: https://github.com/laminas/laminas-i18n/projects/1
