### ISSUE TITLE
Class 'Laminas\Filter\AbstractFilter' not found

### ISSUE THREAD

**Issue by chyzas** [laminas/laminas-i18n#43]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | x.y.z

**Comment by samsonasik** [comment]
you can require laminas-filter yourself, it is in the composer.json's suggest part:

https://github.com/laminas/laminas-i18n/blob/99519a72c3a38ab0522df332a732841517c16332/composer.json#L51
