### ISSUE TITLE
Issue with strpos call in laminas-stdlib when using IsFloat validator

### ISSUE THREAD

**Issue by javabudd** [laminas/laminas-i18n#52]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary

Initial misreported bug https://github.com/laminas/laminas-stdlib/issues/27

It seems when using this library in conjunction with laminas/laminas-stdlib:3.4.0, there is the potential for a boolean argument to be passed into the underlying wrappers `strpos` method, causing an exception to be thrown.

#### Current behavior

\Laminas\I18n\Validator\IsFloat::isValid:243 calls `strpos` and passes in $lastStringGroup which has the potential to be a boolean, causing an exception.

https://github.com/laminas/laminas-i18n/blob/b85a640138687f26129ace789fd24bbe0e0972ad/src/Validator/IsFloat.php#L240-L246

#### How to reproduce

Call \Laminas\I18n\Validator\IsFloat::isValid and pass in a string value (IE "1")

#### Expected behavior

\Laminas\I18n\Validator\IsFloat::isValid should not throw an exception

**Comment by froschdesign** [comment]
@javabudd 
> Call \Laminas\I18n\Validator\IsFloat::isValid and pass in ??? (TBD)

Please provide one or more values that cause the problem. Or create a unit test and send it as a pull request.
Thanks in advance! 👍

**Comment by javabudd** [comment]
Issue seems related to intl version 65.1, will update with a testcase shortly

**Comment by mtodorov1991** [comment]
Im having the same probem. 

        if ((preg_match($lnumSearch, $unGroupedValue)
            || preg_match($dnumSearch, $unGroupedValue)
            || preg_match($expDnumSearch, $unGroupedValue))
            && false === $this->wrapper->strpos($lastStringGroup, $groupSeparator)
        ) {
            return true;
        }

lastStringGroup is false and i get this exception: "TypeError: grapheme_strpos() expects parameter 1 to be string, bool given in file"

**Comment by arokettu** [comment]
Some facts:

1. (for en_GB) single and double digits cause the crash
2. The upstream problem is fixed in PHP 8:
   > substr(), mb_substr(), iconv_substr() and grapheme_substr() now consistently clamp out-of-bounds offsets to the string boundary. Previously, false was returned instead of the empty string in some cases.

The easiest fix is `$lastStringGroup = $this->wrapper->substr($value, -$groupSize) ?: '';` but maybe the string wrapper can be fixed to work correctly in any PHP version?

**Comment by javabudd** [comment]
@arokettu There is a PR fix here: https://github.com/laminas/laminas-i18n/pull/53

This should work for all languages, but it might be helpful to double check for someone in GB

**Comment by WillyBaldy** [comment]
Same problem here, was wondering why some of my unit tests were not passing anymore after I updated Laminas.

**Comment by WillyBaldy** [comment]
Any hope this can be fixed in the near future? My project is still stuck to `"laminas/laminas-stdlib": "~3.3.0"` because of this.

**Comment by froschdesign** [comment]
@WillyBaldy 
You can review the related pull request (#53) and add your comments and suggestions there.
Thanks in advance! 👍

**Comment by dmetzler1988** [comment]
Had the same issue with `laminas/laminas-stdlib` on version `3.5.0`. I also made a downgrade to version `3.3.0`.
Hopefully the pull request (#53) will be merged soon.

**Comment by arokettu** [comment]
I would like to propose a cleaner and simpler solution: #54

**Comment by froschdesign** [comment]
Fixed with #54
