### ISSUE TITLE
Works not with laminas-cache >= 3.0.0

### ISSUE THREAD

**Issue by panvid** [laminas/laminas-i18n#63]
The `composer.json` does not work with `laminas-cache` >= 3.0.0, but does not block this in `require` (only `require-dev`).

With `laminas-cache` 3.0.0 the `Cache\StorageFactory` is removed.

**Comment by froschdesign** [comment]
An update is already planned for the next minor version. [laminas-cache-storage-deprecated-factory](https://github.com/laminas/laminas-cache-storage-deprecated-factory) will be used.
