### ISSUE TITLE
Package is not compatible to required laminas/laminas-cache:^3.1.2

### ISSUE THREAD

**Issue by cindyullmann** [laminas/laminas-i18n#68]
#### Summary

As mentioned in [this commit](https://github.com/laminas/laminas-cache/commit/fe70378e770cdc12940113f91429573dbbdfe89e) static Cache\StorageFactory is no longer available in v3.
laminas/laminas-i18n (v2.14.x-dev) requires laminas/laminas-cache ^3.1.2.

So, when I use laminas-cache v3, i18n\Translator breaks on [line 217](https://github.com/laminas/laminas-i18n/blob/2.14.x/src/Translator/Translator.php#L217).

#### Previous behavior

Cache storage was built.

#### Current behavior

PHP Fatal error:

```
PHP Fatal error:  Uncaught Error: Class "Laminas\\Cache\\StorageFactory" not found in /var/www/html/mediaport/current/vendor/laminas/laminas-i18n/src/Translator/Translator.php:217
```

#### How to reproduce

I just had to install the package and try using the translator.

**Comment by froschdesign** [comment]
> So, when I use laminas-cache v3, i18n\Translator breaks on [line 217](https://github.com/laminas/laminas-i18n/blob/2.14.x/src/Translator/Translator.php#L217).

Install the package [laminas-cache-storage-deprecated-factory](https://github.com/laminas/laminas-cache-storage-deprecated-factory) and it will work.
