### ISSUE TITLE
PhoneNumber validator did not support new 640 area code for US

### ISSUE THREAD

**Issue by ruzann** [laminas/laminas-i18n#73]
### Feature Request

 for example  +16403519451 is valid mobile number in New Jersey, but PhoneNumber validator said that is it not valid

**Comment by Ocramius** [comment]
An example / test case would go a long way here.

**Comment by froschdesign** [comment]
@ruzann 
Please use the new validator `Laminas\I18n\PhoneNumber\Validator\PhoneNumber` and you will get the desired result.

## Installation

```bash
$ composer require laminas/laminas-i18n-phone-number
```

## Basic Usage

```php
$validator = new Laminas\I18n\PhoneNumber\Validator\PhoneNumber();
$validator->isValid('+16403519451'); // true
```

## Learn More

The new validator uses [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) which uses Google's phone number handling library.

See also: https://github.com/laminas/laminas-i18n-phone-number
