### ISSUE TITLE
[RFC]: Use external dependency to validate and format international phone numbers

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-i18n#74]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | current  |
| BC Break?           | hopefully not |

### Background

The phone number validator must take *a lot* of maintenance to keep up with global changes to area codes and number formats etc.

I've used [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) on a number of projects and found it to be well maintained and frequently updated with new information from Google's [libphonenumber](https://github.com/google/libphonenumber) project.

### Proposal(s)

- Add `giggsey/libphonenumber-for-php` as a dependency
- Alter the phone number validator to make use of the library
- Possibly introduce a filter(s) to format phone numbers in local, national, international format.

### Potential BC Breaks

There may not be a 1-1 mapping between the existing possible number types and those found in https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumberType.php

### Appendix

Relevant to issues #73 and #3

**Comment by Ocramius** [comment]
IMO not to be dragged into `laminas/laminas-i18n`, but into something like `laminas/laminas-i18n-phone-number`, which would then be an adapter with the declared external dependency.

**Comment by gsteel** [comment]
@Ocramius - would you expect to drop the validator here in a future major of `i18n`? I've probably got most of what would be needed here in other projects…

**Comment by Ocramius** [comment]
> would you expect to drop the validator here in a future major of `i18n`?

Something like that, with a smooth migration path (find/replace-only, perhaps)

**Comment by gsteel** [comment]
@Ocramius - Here's an initial stab at `laminas-i18n-phone-number` https://github.com/gsteel/laminas-i18n-phone-number

**Comment by Ocramius** [comment]
@gsteel IMO bring it up with next TSC agenda?

**Comment by gsteel** [comment]
Also relevant to #77 - Closing this now pending introduction of the new lib at https://github.com/laminas/laminas-i18n-phone-number
