### ISSUE TITLE
Australian internal number not accepted by the mobile number validator

### ISSUE THREAD

**Issue by DominiqueSteenman** [laminas/laminas-i18n#77]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13

#### Summary

We have a customer that wants to add an australian mobile number, but the validator is saying its false.

#### Current behavior

The output is false while it should be true, international number to australia start with 06 instead of 04.

#### How to reproduce

Use allowed_types: mobile
Use number: 0061 4 75673255
Output: false on AU

#### Expected behavior

Output: true on AU

**Comment by froschdesign** [comment]
> The output is false while it should be true, international number to australia start with 06 instead of 04.

Google's [libphonenumber](https://github.com/google/libphonenumber) says this number is possible but not valid:

https://libphonenumber.appspot.com/phonenumberparser?number=0061+4+75673255&country=AU

**Comment by eduardvdberg** [comment]
i have the same problem:

475673255 is a valid AU cellphone number and this one does validate as true.
https://libphonenumber.appspot.com/phonenumberparser?number=475673255&country=AU

But if i test this with the regex used in the vendor/laminas/laminas-i18n/src/Validator/PhoneNumber/AU.php for mobile
^(?:14(?:5\d|71)\d{5}|4(?:[0-2]\d|3[0-57-9]|4[47-9]|5[0-35-9]|6[6-9]|[79][07-9]|8[17-9])\d{6})$
it doesn't validate to true because of the \d{6})$.  If i turn this to \d{7})$ it will validate to true

**Comment by froschdesign** [comment]
> i have the same problem:

This is a different number with other results:

```php
$number = '475673255';

$validator = new Laminas\I18n\Validator\PhoneNumber(
    [
        'country' => 'AU',
    ]
);
var_dump($validator->isValid($number)); // true

$validator = new Laminas\I18n\Validator\PhoneNumber(
    [
        'country'       => 'AU',
        'allowed_types' => ['mobile'],
    ]
);
var_dump($validator->isValid($number)); // false

$validator = new Laminas\I18n\Validator\PhoneNumber(
    [
        'country'        => 'AU',
        'allow_possible' => true,
    ]
);
var_dump($validator->isValid($number)); // true

$validator = new Laminas\I18n\Validator\PhoneNumber(
    [
        'country'        => 'AU',
        'allowed_types'  => ['mobile'],
        'allow_possible' => true,
    ]
);
var_dump($validator->isValid($number)); // true
```

**Comment by froschdesign** [comment]
Btw. the support for Google's libphonenumber is on the way: https://github.com/laminas/laminas-i18n-phone-number

**Comment by DominiqueSteenman** [comment]
Aah okay, now the customer said the number is +61475673255 (they are kinda starting to annoy me lol)
Which is accepted by google's libphonenumber but not by the current laminas check.

https://libphonenumber.appspot.com/phonenumberparser?number=+61475673255&country=AU

Guess i'll wait for the googlelib's one then. :)
